export enum LocalLLMErrorCode {
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  MODEL_TOO_LARGE = 'MODEL_TOO_LARGE',
  CONTEXT_CREATE_FAILED = 'CONTEXT_CREATE_FAILED',
  CONTEXT_EXHAUSTED = 'CONTEXT_EXHAUSTED',
  INFERENCE_FAILED = 'INFERENCE_FAILED',
  STREAM_FAILED = 'STREAM_FAILED',
  DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
  DOWNLOAD_INTEGRITY_MISMATCH = 'DOWNLOAD_INTEGRITY_MISMATCH',
  VISION_FAILED = 'VISION_FAILED',
  VISION_FETCH_FAILED = 'VISION_FETCH_FAILED',
  EMBEDDING_FAILED = 'EMBEDDING_FAILED',
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  INVALID_PATH = 'INVALID_PATH',
  CACHE_CORRUPT = 'CACHE_CORRUPT',
  QUANTIZE_FAILED = 'QUANTIZE_FAILED',
  INSUFFICIENT_MEMORY = 'INSUFFICIENT_MEMORY',
}

export class LocalLLMError extends Error {
  readonly code: LocalLLMErrorCode;

  constructor(code: LocalLLMErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = 'LocalLLMError';
    this.code = code;
  }
}
